# Importação e carregamento dos dados

In [12]:
!pip install category_encoders

# Tratamento de dados
import pandas as pd
import numpy as np

# Bibliotecas para EDA
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FunctionTransformer
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Não exisbir warnings
import warnings
warnings.filterwarnings("ignore")

# Fazendo o ggplot ser o estilo padrao de todos os plots
plt.style.use('ggplot')

# Configurar para exibir ate 15 linhas de um DF em pandas e para mostrar todas as colunas
pd.set_option('display.max_rows', 15)
pd.set_option('display.max_columns', None)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 1.0 MB/s eta 0:00:00


In [13]:
churn = pd.read_csv('Churn Modeling.csv')
churn.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [14]:
churn.shape

(10000, 14)

In [15]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [16]:
churn.describe()


RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# Preprocessamento

In [17]:
churn.drop(columns=['RowNumber', 'CustomerId'],inplace=True)

In [18]:
from sklearn.model_selection import train_test_split

X = churn.drop(['Exited'], axis=1)
y = churn['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8500, 11), (1500, 11), (8500,), (1500,))

In [20]:
X_train

Surname  CreditScore Geography  Gender  Age  Tenure    Balance  \
8701         Onio          673    France    Male   37       2       0.00   
3429      Bradley          731   Germany  Female   43       9   79120.27   
8870        Clark          668    France    Male   42       8  187534.79   
6962       Fraser          677   Germany  Female   26       3  102395.79   
2088       Nnaife          595   Germany  Female   41       9  150463.11   
...           ...          ...       ...     ...  ...     ...        ...   
5734    Henderson          768    France    Male   54       8   69712.74   
5191  Chukwualuka          682    France  Female   58       1       0.00   
5390    Macrossan          735    France  Female   38       1       0.00   
860      McGregor          667    France    Male   43       8  190227.46   
7270        Smith          697   Germany    Male   51       1  147910.30   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
8701              1          1               1         13624.02  
3429              1          0               0           548.52  
8870              1          1               1         32900.41  
6962              1          1               0        119368.99  
2088              2          0               1         81548.38  
...             ...        ...             ...              ...  
5734              1          1               1         69381.05  
5191              1          1               1           706.50  
5390              3          0               0         92220.12  
860               1          1               0         97508.04  
7270              1          1               1         53581.14  

[8500 rows x 11 columns]

In [21]:
# Depois fazer uma analise mais aprofundada se tem alguma coluna que está como float ou int mas na verdade representa uma categoria
# Talvez dividir as cvategiricas em orginal  categorica
categorical_features = ['Surname', 'Geography', 'Gender']
numerical_features = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']

In [22]:
from category_encoders import OneHotEncoder
from sklearn.discriminant_analysis import StandardScaler


numerical_pipe = Pipeline(steps=[
    # Testar outras estrategias como normalizar, polynomial features, ...
    ('scaler', StandardScaler())
])

categorical_pipe = Pipeline(steps=[
    # Testar outros encoders
    ('cat_encoder', OneHotEncoder())
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_pipe, numerical_features),
    ('cat', categorical_pipe, categorical_features),
])

# Random Forest

## Fit

In [23]:
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classificador', RandomForestClassifier()) # Testar outro modelo e tunar os parametros
])

In [24]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat',
                                                  Pipeline(steps=[('cat_encoder',
                                                                   OneHotEncoder())]),
                                                  ['Surname', 'Geography',
                                                   'Gender'])])),
                ('classificador', RandomForestClassifier())])

## Metrics

In [25]:
from sklearn.metrics import accuracy_score, precision_score, roc_auc_score, confusion_matrix, f1_score, recall_score

y_pred = model.predict(X_test)

print(f'Acurracia: {accuracy_score(y_test, y_pred)}')
print(f'F1-score: {f1_score(y_test, y_pred)}')
print(f'Preision: {precision_score(y_test, y_pred)}')
print(f'recall: {recall_score(y_test, y_pred)}')

Acurracia: 0.8546666666666667
F1-score: 0.480952380952381
Preision: 0.7952755905511811
recall: 0.3447098976109215


In [26]:
print('Matriz de confusão: \n', confusion_matrix(y_test, y_pred)) # Aumentar ou diminuir a certeza com base na matriz de confusao

Matriz de confusão: 
 [[1181   26]
 [ 192  101]]


# Logistic Regression

## Fit

In [27]:
from sklearn.linear_model import LogisticRegression

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classificador', LogisticRegression())
])

In [28]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat',
                                                  Pipeline(steps=[('cat_encoder',
                                                                   OneHotEncoder())]),
                                                  ['Surname', 'Geography',
                                                   'Gender'])])),
                ('classificador', LogisticRegression())])

## Metrics

In [29]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

Accuracy: 0.8106666666666666
F1 Score: 0.3004926108374384
Precision: 0.5398230088495575
Recall: 0.20819112627986347


In [30]:
print('Matriz de confusão: \n', confusion_matrix(y_test, y_pred))

Matriz de confusão: 
 [[1155   52]
 [ 232   61]]


# Naive Bayes

## Fit

In [31]:
from sklearn.naive_bayes import GaussianNB

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classificador', GaussianNB())
])

In [32]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat',
                                                  Pipeline(steps=[('cat_encoder',
                                                                   OneHotEncoder())]),
                                                  ['Surname', 'Geography',
                                                   'Gender'])])),
                ('classificador', GaussianNB())])

## Metrics

In [33]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

Accuracy: 0.332
F1 Score: 0.3022284122562674
Precision: 0.18985126859142606
Recall: 0.7406143344709898


In [34]:
print('Matriz de confusão: \n', confusion_matrix(y_test, y_pred))

Matriz de confusão: 
 [[281 926]
 [ 76 217]]


# KNN

## Fit

In [35]:
from sklearn.neighbors import KNeighborsClassifier

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classificador', KNeighborsClassifier())
])

In [36]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat',
                                                  Pipeline(steps=[('cat_encoder',
                                                                   OneHotEncoder())]),
                                                  ['Surname', 'Geography',
                                                   'Gender'])])),
                ('classificador', KNeighborsClassifier())])

## Metrics

In [37]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

Accuracy: 0.8413333333333334
F1 Score: 0.5122950819672131
Precision: 0.6410256410256411
Recall: 0.42662116040955633


In [38]:
print('Matriz de confusão: \n', confusion_matrix(y_test, y_pred))

Matriz de confusão: 
 [[1137   70]
 [ 168  125]]
